defaults:
  - dataset: Asian
  - _self_

paths:
  dataset: ./dataset/
  raw: ./dataset/raw
  processed: ./dataset/processed

  splits: ${paths.processed}/${dataset.category}/splits
  combined: ${paths.processed}/${dataset.category}/combined
  filtered: ${paths.processed}/${dataset.category}/filtered

  meta: ${paths.filtered}/meta
  review: ${paths.filtered}/review

  result: ./results/${dataset.category}
  users: ./users/${dataset.category}
  graph: ./graphs/${dataset.category}
  embedding: ./embeddings/${dataset.category}
  logs: ./logs/${dataset.category}
  plots: ${paths.result}/plots/models/${name}/

hydra:
  run:
    dir: outputs/${hydra.job.config_name}/${now:%Y-%m-%d_%H-%M-%S}