paths:
  dataset: ./dataset/
  raw: ./dataset/raw
  processed: ./dataset/processed

  splits: ${paths.processed}/${dataset.country}/splits
  combined: ${paths.processed}/${dataset.country}/combined
  filtered: ${paths.processed}/${dataset.country}/filtered

  meta: ${paths.filtered}/meta
  review: ${paths.filtered}/review

  result: ./results/${dataset.country}
  graph: ./graphs/${dataset.country}
  embedding: ./embeddings/${dataset.country}
  logs: ./logs/${dataset.country}
  plots: ${paths.result}/plots/models/${name}/

dataset:
  min_num_reviews: 5
  min_rating: 4
  country: Asian
  meta_keys: [gmap_id, name, address, latitude, longitude, category, avg_rating, num_of_reviews, price, hours]
  review_keys: [gmap_id, user_id, name, time, rating]

hydra:
  run:
    dir: outputs/${hydra.job.config_name}/${now:%Y-%m-%d_%H-%M-%S}