name: gcl_temp_0.2_reg_0.05_eps_0.2

defaults:
  - base
  - _self_

training:
  batch_size: 1024
  device: cuda
  n_epochs: 1000
  early_stopping: 20
  lr: 0.001
  reg_weight: 0.0001

  gcl_reg: 0.05
  gcl_eps: 0.2
  gcl_temp: 0.2

evaluation:
  batch_size: 1024
  rank: 20

model:
  embedding_dim: 64
  n_layers: 3