dataset:
  min_num_reviews: 5
  min_rating: 4
  category: Japanese
  meta_keys: [gmap_id, name, address, latitude, longitude, category, avg_rating, num_of_reviews, price, hours]
  review_keys: [gmap_id, user_id, name, time, rating]