name: reg_0.001

defaults:
  - base
  - _self_

training:
  batch_size: 1024
  device: cuda
  n_epochs: 1000
  early_stopping: 20
  lr: 0.001
  reg_weight: 0.001

evaluation:
  batch_size: 1024
  rank: 20

model:
  embedding_dim: 64
  n_layers: 3