defaults:
  - base
  - _self_

embeddings:
  - name: LightGCN Baseline (Dot)
    type: dot
    model: baseline

  - name: LightGCN Baseline (Cosine)
    type: cosine
    model: baseline

  - name: LightGCN Baseline (Distance)
    type: distance
    model: baseline

  - name: LightGCN Best (Dot)
    type: dot
    model: best

  - name: LightGCN Best (Cosine)
    type: cosine
    model: best

  - name: LightGCN Best (Distance)
    type: distance
    model: best

baselines: ["KNN", "Popularity"]

test:
  device: cuda
  batch_size: 1024
  rank: 20

inference:
  min_num_reviews: 10
  num_samples: 50
  topk: 20
  log:
    type: dot
    model: best
    user_ids: []