defaults:
  - base
  - _self_

test:
  device: cuda
  batch_size: 1024
  rank: 20
  embeddings: [
    [LightGCN Baseline (Dot), dot, baseline],
    [LightGCN Baseline (Cosine), cosine, baseline],
    [LightGCN Baseline (Distance), distance, baseline],
    [LightGCN Best (Dot), dot, emb_512_n_layers_4_reg_0.001_gcl_temp_0.2_geo_distance_neighbors_4_weight_1.0],
    [LightGCN Best (Cosine), cosine, emb_512_n_layers_4_reg_0.001_gcl_temp_0.2_geo_distance_neighbors_4_weight_1.0],
    [LightGCN Best (Distance), distance, emb_512_n_layers_4_reg_0.001_gcl_temp_0.2_geo_distance_neighbors_4_weight_1.0],
  ]
  baselines: ["knn", "popularity"]
